// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSeGDGUSBoDDwsXb4bI7ioZSoy9K7YRps',
    appId: '1:750820710962:web:8117e8e61386298acafa2b',
    messagingSenderId: '750820710962',
    projectId: 'ecotripp-4e5db',
    authDomain: 'ecotripp-4e5db.firebaseapp.com',
    storageBucket: 'ecotripp-4e5db.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZlO8Hwu1-FnLFVBQ9g0LE92xy_mQxhKg',
    appId: '1:750820710962:android:3b6971bd80f19628cafa2b',
    messagingSenderId: '750820710962',
    projectId: 'ecotripp-4e5db',
    storageBucket: 'ecotripp-4e5db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKTA8_iB_iKxER9k4nMdsmRatA3MFsuZI',
    appId: '1:750820710962:ios:dd3031c01ec3a691cafa2b',
    messagingSenderId: '750820710962',
    projectId: 'ecotripp-4e5db',
    storageBucket: 'ecotripp-4e5db.appspot.com',
    iosBundleId: 'com.example.ecoTrip',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKTA8_iB_iKxER9k4nMdsmRatA3MFsuZI',
    appId: '1:750820710962:ios:ba0ff9be7ed150accafa2b',
    messagingSenderId: '750820710962',
    projectId: 'ecotripp-4e5db',
    storageBucket: 'ecotripp-4e5db.appspot.com',
    iosBundleId: 'com.example.ecoTrip.RunnerTests',
  );
}
